### ISSUE TITLE
Where are the utilities?

### ISSUE THREAD

**Issue by DavidBruchmann** [Johannestegner/php-utilities#1]
Being amazed by your xml-parser I'd appreciate further magic in PHP ;-)

**Comment by Johannestegner** [comment]
Hehe, happy to hear!
This repo has been moved and further developed at my organisations repository at:  
https://github.com/jitesoft/php-datastructures
https://packagist.org/packages/jitesoft/datastructures

**Comment by DavidBruchmann** [comment]
Thanks, saw it already but never had a closer look yet.
